name: Deploy

run-name: test environment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to cPanel
        id: deploy
        uses: pinkasey/cpanel-deploy-action@v1.0.0
        with:
          hostname: '{{ secrets.CPANEL_HOST }}'
          repository_root: '/home/my_account/repositories/my_repository'
          branch: main
          username: '${{ secrets.CPANEL_USERNAME }}'
          secretKey: '${{ secrets.CPANEL_USERNAME }}'
      - name: echo deploy-duration
        run: echo "Deployment took ${{ steps.deploy.outputs.duration }} milliseconds"