name: Deploy

run-name: test environment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to cPanel
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.CPANEL_HOST }}
          port: 22
          username: ${{ secrets.CPANEL_USERNAME }}
          privateKey: ${{ secrets.CPANEL_SSH_KEY }}
          command: whoami