name: Deploy

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Build Vue app
        run: npm run build

      - name: Deploy to cPanel
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USERNAME }}
          key: ${{ secrets.CPANEL_SSH_KEY }}
          port: 22
          source: "dist"
          target: "sites/stephanebeaumontjardinier.com"
          exclude: |
            **/.git**
            **/.git*/**
            **/node_modules/**
            **/.**